### ISSUE TITLE
#4 Filtering Part 1

### ISSUE THREAD

**Issue by hebronmekuria** [hebronmekuria/MajortoCareer#4]
Feed job description and title into LLM and get a boolean result based on the following prompt:

Answer these questions in two sequences:
1. Can the job be obtained with someone with a bachelor's degree?
2. If so, what undergraduate major would be required?

**Comment by hebronmekuria** [comment]
Should the columns holding the majors all be set to accommodate jobs that require multiple majors?

**Comment by hebronmekuria** [comment]
Output is either No or the major/majors required

**Comment by hebronmekuria** [comment]
Use mock data while waiting for previous steps to be completed.

**Comment by NatiSeifu** [comment]
Done
